node('nodejs') {
    stage('Checkout') {
git url: 'https://github.com/imejri/DO400-apps', branch: 'scripted-pipelines'
    }
    stage('Test') {
        sh 'node ./simple-webapp/backend/test.js'
        sh 'node ./simple-webapp/frontend/test.js'
    } 
}